### ISSUE TITLE
Remove node-git dependency to simplify client requirements 

### ISSUE THREAD

**Issue by cgewecke** [codechecks/monorepo#11]
Message is:
```
[nodegit] WARN - Could not finish postinstall
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/.npm/_npx/9492/lib/node_modules/cgewecke-cc-testing/node_modules/nodegit/build/Release/nodegit.node)
```

It's a [known node-git issue](https://www.npmjs.com/package/nodegit#getting-started)  and can be resolved by adding the following to travis.yml:
```yml
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
```
